-- 切换库
USE moyebi;

-- 更新用户表
ALTER TABLE user
    MODIFY COLUMN id BIGINT AUTO_INCREMENT COMMENT 'id',
    MODIFY COLUMN userAccount VARCHAR(256) NOT NULL COMMENT '账号',
    MODIFY COLUMN userPassword VARCHAR(512) NOT NULL COMMENT '密码',
    MODIFY COLUMN userName VARCHAR(256) NULL COMMENT '用户昵称',
    MODIFY COLUMN userAvatar VARCHAR(1024) NULL COMMENT '用户头像',
    MODIFY COLUMN userRole VARCHAR(256) DEFAULT 'user' NOT NULL COMMENT '用户角色：user/admin',
    MODIFY COLUMN createTime DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT '创建时间',
    MODIFY COLUMN updateTime DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    MODIFY COLUMN isDelete TINYINT DEFAULT 0 NOT NULL COMMENT '是否删除';



-- 更新图表表
ALTER TABLE chart
    MODIFY COLUMN id BIGINT AUTO_INCREMENT COMMENT 'ID',
    MODIFY COLUMN goal TEXT NULL COMMENT '分析目标',
    MODIFY COLUMN chartData TEXT NULL COMMENT '图表数据',
    MODIFY COLUMN chartType VARCHAR(128) NULL COMMENT '图表类型',
    MODIFY COLUMN genChart TEXT NULL COMMENT '生成的图表数据',
    MODIFY COLUMN genResult TEXT NULL COMMENT '生成的分析结论',
    MODIFY COLUMN userId BIGINT NULL COMMENT '创建用户 id',
    MODIFY COLUMN createTime DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT '创建时间',
    MODIFY COLUMN updateTime DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    MODIFY COLUMN isDelete TINYINT DEFAULT 0 NOT NULL COMMENT '是否删除',
    MODIFY COLUMN `name` VARCHAR(128) NULL COMMENT '图表名称',
    MODIFY COLUMN status VARCHAR(128) DEFAULT 'wait' NOT NULL COMMENT '图表状态',
    MODIFY COLUMN execMessage TEXT NULL COMMENT '图表状态执行信息',
    MODIFY COLUMN retry INT DEFAULT 0 NOT NULL COMMENT '图表分析重试次数';


-- 更新积分表
ALTER TABLE score
    MODIFY COLUMN id BIGINT AUTO_INCREMENT COMMENT 'id' PRIMARY KEY,
    MODIFY COLUMN userId BIGINT COMMENT '创建用户id',
    MODIFY COLUMN scoreTotal BIGINT DEFAULT 0 NULL COMMENT '总积分',
    MODIFY COLUMN isSign TINYINT DEFAULT 0 COMMENT '0表示未签到，1表示已签到',
    MODIFY COLUMN createTime DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT '创建时间',
    MODIFY COLUMN updateTime DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    MODIFY COLUMN isDelete TINYINT DEFAULT 0 NOT NULL COMMENT '是否删除';
